eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.2.79:8761/eureka/

  instance:
    hostname: localhost

server:
  port: 8082

spring:
  application:
    name: TimeDelay_Async